language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .

script: python run_tests.py

matrix:
  allow_failures:
    - python: "2.6"
