language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5

before_install:
  - export PIP_USE_MIRRORS=true

install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .

script: python run_tests.py
