language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=">=1.4,<1.5"
  - DJANGO_VERSION="==1.5"
  - DJANGO_VERSION=">=1.5,<1.6"
  - DJANGO_VERSION="==1.6"
  - DJANGO_VERSION=">=1.6,<1.7"
  - DJANGO_VERSION="==1.7"
  - DJANGO_VERSION=">=1.7,<1.8"
  - DJANGO_VERSION="==1.8"
  - DJANGO_VERSION=">=1.8,<1.9"
  - DJANGO_VERSION="==1.9"
  - DJANGO_VERSION=">=1.9,<1.10"

# https://docs.djangoproject.com/en/1.9/releases/1.8/#python-compatibility
# https://docs.djangoproject.com/en/1.9/releases/1.9/#python-compatibility

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION="==1.7"
    - python: "2.6"
      env: DJANGO_VERSION=">=1.7,<1.8"
    - python: "2.6"
      env: DJANGO_VERSION="==1.8"
    - python: "2.6"
      env: DJANGO_VERSION=">=1.8,<1.9"
    - python: "2.6"
      env: DJANGO_VERSION="==1.9"
    - python: "2.6"
      env: DJANGO_VERSION=">=1.9,<1.10"

    - python: "3.2"
      env: DJANGO_VERSION=">=1.4,<1.5"
    - python: "3.2"
      env: DJANGO_VERSION="==1.9"
    - python: "3.2"
      env: DJANGO_VERSION=">=1.9,<1.10"


    - python: "3.3"
      env: DJANGO_VERSION=">=1.4,<1.5"
    - python: "3.3"
      env: DJANGO_VERSION="==1.9"
    - python: "3.3"
      env: DJANGO_VERSION=">=1.9,<1.10"

    - python: "3.4"
      env: DJANGO_VERSION=">=1.4,<1.5"

    - python: "3.5"
      env: DJANGO_VERSION=">=1.4,<1.5"
    - python: "3.5"
      env: DJANGO_VERSION="==1.5"
    - python: "3.5"
      env: DJANGO_VERSION=">=1.5,<1.6"
    - python: "3.5"
      env: DJANGO_VERSION="==1.6"
    - python: "3.5"
      env: DJANGO_VERSION=">=1.6,<1.7"
    - python: "3.5"
      env: DJANGO_VERSION="==1.7"
    - python: "3.5"
      env: DJANGO_VERSION=">=1.7,<1.8"


install:
  - pip install Django$DJANGO_VERSION
  - pip install flake8
  - pip install -e .

script:
  - make flake8
  - make test
